language: node_js
node_js: '6'
dist: trusty
sudo: required
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable xvfb
cache:
  directories:
    - node_modules
    - $HOME/.cache/bower
before_script:
- npm run lint
script:
  - xvfb-run npm run test
notifications:
  slack:
    secure: ng5J65HBX59Brd80nWejwt1/HrOAAFBTL72RMJJ2+ZrKcgwNjV2vGnomROFgXrHVEtafzoL8Jtopb0FddRcD5RWdMHELfv3i29qTDTJiUHIbrZ5T7oVJTz8TXpfyIcPkKcECd6EWnHDxLwbvVVxX8n9hF61cat+XXARd5C/e9I/llFl9NgMQf71Co0z4sBTEdbLUOfsnfe3MSiisPbgJT2KrNrcrR4DW1n7XgmMjf1CFIlFTIdIDCTNV8SNIVa2D65gNZpm7AcyYj9mdQrfG32UHnS+drOQUTlw9euq0Ie9BM7mTsf50+0qHHoU6mY3XtZIQwRqBrTxL19gLIewxziT6n86c0Ur8H4NvkUIsNTlO3lozGiJXWCx6BbEjCeTFnovjdo+6hTYbET92xRmC2ex3vDqz/1JTDE79Ta6CTrzeDSDcPOOApbAXec4y1Fbm54gHpzjdFNiUaqEObTLpUpNOzLxdoeStlkpZ5F8dy3jO1iiPjwGI6AF/T0No178XkMrBSYbX+DbzfnzEOPRjFmT9MjzrvPpQmucMXwpd5OE/Rm8TgGfIyHNKwr8G24LIU3gQJg0kxfExwwALPMJvo6VW5kt2z7PokHvRxTGrO8DdLgT7VMLZPbg6NLBTMaMKUuJNPjHSz9kKLXcK1D/JUW1S/IiQLIc9ebVW/cONCi4=
